name: calorie_burn
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  provider: ^6.1.2
  health: ^11.1.1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  camera: ^0.11.1+1
  path_provider: ^2.1.3
  path: ^1.9.0
  http: ^1.2.2
  flutter_dotenv: ^5.1.0

  # 수정: 백그라운드 동기화 기능을 위해 패키지 추가
  background_fetch: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env